version: '3.8'
services:
  opentutor:
    container_name: opentutor
    build:
      context: .
      dockerfile: ./docker/Dockerfile
  cypress:
    container_name: cypress
    depends_on:
      - opentutor
    build:
      context: cypress
    environment:
      - CYPRESS_BASE_URL=http://opentutor
      - CYPRESS_SNAPSHOT_DIFF_DIR=/app/cypress/snapshots/snapshot_failed_diffs
      - GRAPHQL_ENDPOINT=/graphql
      - TUTOR_ENDPOINT=/tutor
      - ADMIN_ENDPOINT=/admin