version: '3.8'
services:
  home:
    image: apache
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: apache
    restart: always
    ports:
      - "8000:80"
  e2e:
    image: cypress
    build:
      context: ./cypress
    container_name: cypress
    depends_on:
      - home
    environment:
      - CYPRESS_BASE_URL=http://home/home
      - GRAPHQL_ENDPOINT=/graphql
      - TUTOR_ENDPOINT=/tutor
      - ADMIN_ENDPOINT=/admin
    command: npx cypress run
    volumes:
      - ./cypress/cypress:/app/cypress
      - ./cypress/cypress.config.ts:/app/cypress.config.ts