name: test commit
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: cd client && npm ci
      - name: audit
        run: cd client && npm run test:audit
      - name: format
        run: cd client && npm run test:format
      - name: lint
        run: cd client && npm run test:lint
      - name: types
        run: cd client && npm run test:types
      - name: license
        run: cd client && npm run test:license
  test-e2e:
    name: test e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: app start in docker-compose
        run: docker-compose up -d
      - name: test services running
        run: docker ps
      - name: cypress run tests
        run: make test-e2e-exec
      - name: failed - retrieve image diffs
        run: make test-e2e-image-snapshots-copy && mkdir -p cypress/cypress/snapshots/snapshot_failed_diffs
        if: ${{ failure() }}
      - name: failed - upload image-diff artifacts
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: snapshot_failed_diffs
          path: cypress/cypress/snapshots
  publish-check:
    name: publish check
    needs:
      - test
      - test-e2e
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.is_release.outputs.is_release }}
    steps:
      - id: is_release
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-[a-z0-9.]*$ ]]; then
              echo ::set-output name=is_release::true
          fi
  build-and-publish:
    name: build + push docker image
    runs-on: ubuntu-latest
    needs:
      - publish-check
      - test
      - test-e2e
    if: needs.publish-check.outputs.is_release || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: docker tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo ::set-output name=image_tag::${IMAGE_TAG}
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: export DOCKER_IMAGE=uscictdocker/opentutor-home:${{ steps.tag.outputs.image_tag }} && make docker-build
      - name: docker tag release as version
        if: needs.publish-check.outputs.is_release == 'true'
        run: docker tag "uscictdocker/opentutor-home:${{ steps.tag.outputs.image_tag }}" "uscictdocker/opentutor-home:${GITHUB_REF#refs/tags/}"
      - name: docker tag main as latest
        if: github.ref == 'refs/heads/main'
        run: docker tag "uscictdocker/opentutor-home:${{ steps.tag.outputs.image_tag }}" "uscictdocker/opentutor-home:latest"
      - name: docker push
        run: docker push uscictdocker/opentutor-home
